const CONST_PAGE_COUNT_EVENT = {
	ADD_UNIT_NUM: 'ADD_UNIT_NUM',
	PASS_UNIT_NUM: 'PASS_UNIT_NUM',
	FAIL_UNIT_NUM: 'FAIL_UNIT_NUM'
}
Object.freeze(CONST_PAGE_COUNT_EVENT)
export default CONST_PAGE_COUNT_EVENT
